---
apiVersion: v1
kind: Secret
metadata:
  name: credentials_azs
type: Opaque
stringData:
  MARIADB_USER: root	
  MARIADB_PASSWORD: root
  MARIADB_DATABASE: azship_freight
  MARIADB_ROOT_PASSWORD: root
  # O host deve ser o nome do container MariaDB especificado no docker-compose, se estiver usando o Docker
  MARIADB_HOST: mariadb
  MARIADB_PORT: 3306
