CREATE DATABASE IF NOT EXISTS azship_freight;

USE azship_freight;

DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CLIENTE (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	RAZAO_SOCIAL VARCHAR(200),
	NOME_FANTASIA VARCHAR(200),
	CNPJ VARCHAR(14) UNIQUE,
	CRIADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP,
	CPF VARCHAR(11) UNIQUE,
	NOME_PESSOA VARCHAR(100)
);

CREATE INDEX IDX_CLIENTE_NOME_PESSOA ON CLIENTE(NOME_PESSOA);
CREATE INDEX IDX_CLIENTE_CPF ON CLIENTE(CPF);
CREATE INDEX IDX_CLIENTE_CNPJ ON CLIENTE(CNPJ);
CREATE INDEX IDX_CLIENTE_NOME_FANTASIA ON CLIENTE(NOME_FANTASIA);
CREATE INDEX IDX_CLIENTE_RAZAO_SOCIAL ON CLIENTE(RAZAO_SOCIAL);

DROP TABLE IF EXISTS FRETE;

CREATE TABLE FRETE (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	CLIENTE_ID BIGINT NOT NULL,
	NOME_PRODUTO VARCHAR(200) NOT NULL,
	DESCRICAO_PRODUTO VARCHAR(500),
	SKU VARCHAR(100),
	CODIGO_EXTERNO VARCHAR(100),
	PESO_KG BIGINT,
	CUBAGEM BIGINT,
	PAIS_ORIGEM VARCHAR(50) NOT NULL,
	PAIS_DESTINO VARCHAR(50) NOT NULL,
	ESTADO_ORIGEM VARCHAR(100) NOT NULL,
	ESTADO_DESTINO VARCHAR(100) NOT NULL,
	CEP_DESTINO VARCHAR(11) NOT NULL,
	ENDERECO_DESTINO VARCHAR(500) NOT NULL,
	VALOR_FRETE DECIMAL(20,2) NOT NULL,
	MOEDA_FRETE ENUM('USD', 'BRL', 'EUR') NOT NULL,
	CRIADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP,
	DATA_ESTIMADA_ENTREGA DATE NOT NULL,
	
	CONSTRAINT FK_FRETE_CLIENTE_ID FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(ID) ON DELETE NO ACTION
);

CREATE INDEX IDX_FRETE_CLIENTE_ID ON FRETE(CLIENTE_ID);
CREATE INDEX IDX_FRETE_NOME_PRODUTO ON FRETE(NOME_PRODUTO);
CREATE INDEX IDX_FRETE_DESCRICAO_PRODUTO ON FRETE(DESCRICAO_PRODUTO);
CREATE INDEX IDX_FRETE_SKU ON FRETE(SKU);
CREATE INDEX IDX_FRETE_CODIGO_EXTERNO ON FRETE(CODIGO_EXTERNO);
CREATE INDEX IDX_FRETE_CRIADO_EM ON FRETE(CRIADO_EM);
CREATE INDEX IDX_FRETE_DATA_ESTIMADA_ENTREGA ON FRETE(DATA_ESTIMADA_ENTREGA);

GRANT ALL privileges ON azship_freight.* TO 'admin'@'%';

FLUSH PRIVILEGES;
